export enum ACTION_TYPES {
  FETCH_LIST_CARD = '@@LIST_CARDR/FETCH',
  SET_LIST_CARD = '@@LIST_CARD/SET',
  TOOGLE_LIST = '@@LISCT_CARD/TOGGLE_LIST',
  TOOGLE_TEXT = '@@LISCT_CARD/TOGGLE_TEXT',
  TOOGLE_EDIT = '@@LISCT_CARD/TOGGLE_EDIT'
}
