export enum ACTION_TYPES {
  FETCH_LIST = '@@BOARDS_LIST/FETCH',
  SET_BOARDSLIST = '@@BOARDS_LIST/SET',
  TOOGLE_EDIT_LIST = '@@BOARDS_LIST/TOOGLE_EDIT_LIST',
  SET_EDIT_LIST = '@@BOARDS_LIST/SET_EDIT_LIST',
  CREATE_NEW_CARD = '@@@BOARDS_LIST/CREATE_NEW_CARD'
}
